import { Figtree } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

const figtree = Figtree({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-figtree',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${figtree.className} flex min-h-screen flex-col justify-between antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
